### ISSUE TITLE
Gui object has no attribute 'repack' 

### ISSUE THREAD

**Issue by ranjian0** [kxgames/glooey#17]
Resizing pyglet window produces 
`
AttributeError: 'Gui' object has no attribute 'repack'
`

In `root.py` line `118`:
 `self.repack` should be renamed to  `self._repack`

Regression from 1385b85c205d388409cf283e4f7704fc5f2ca5e7

**Comment by ranjian0** [comment]
Just noticed: similar to issue #15

**Comment by kalekundert** [comment]
Sorry for being unresponsive; for some reason I wasn't getting email notifications for this project.  I just pushed a fix, you should be able to resize windows again.
